version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-event
    container_name: backend-event
    ports:
      - ${PORT}:${PORT}
    environment:
      STAGE: ${STAGE}
      PORT: ${PORT}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    container_name: eventdb
    volumes:
      - ./postgres:/var/lib/postgresql/data
  pgAdmin: 
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    restart: always
    ports:
      - "4000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    container_name: pgEvent
    volumes:
      - ./pgAdmin:/var/lib/pgadmin
    

    